### ISSUE TITLE
Read me file in english.

### ISSUE THREAD

**Issue by govi20** [oldratlee/fucking-java-concurrency#2]
It would be nice if someone can extend the readme file with proper conversion.

**Comment by oldratlee** [comment]
😸 OK, I can do this.

PS: Your attention is my pleasure.

**Comment by PieChuckerr** [comment]
Thank you sir.

**Comment by govi20** [comment]
Do you want me convert it using translator. As you are native, you can review and fix the translation.

**Comment by oldratlee** [comment]
> Do you want me convert it using translator.

@govi20 YES. Good suggestions ❤️  Thanks for your contribution!

\# It's a pain to do translation for me. 😖😜

**Comment by ilyastuit** [comment]
Any news?

**Comment by oldratlee** [comment]
@govi20 @ilyastuit 

add the english README.

Sorry for my protracted reply... 😖
